// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnZ5p6pCM7aR7MkIfNftwSm4nhJgPyhZ0',
    appId: '1:942977102864:web:6517947890794bb35cc695',
    messagingSenderId: '942977102864',
    projectId: 'our-chat-31921',
    authDomain: 'our-chat-31921.firebaseapp.com',
    storageBucket: 'our-chat-31921.appspot.com',
    measurementId: 'G-6X83K3038Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByU3Hz-G1Tf0YD_YgC3vs5xibfX6bz9bM',
    appId: '1:942977102864:android:3a4e6a01f2183cd85cc695',
    messagingSenderId: '942977102864',
    projectId: 'our-chat-31921',
    storageBucket: 'our-chat-31921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1VrN6pL6cx7Y0GQhbmzq8aFsLd1o2r7g',
    appId: '1:942977102864:ios:9206b323aba44c5a5cc695',
    messagingSenderId: '942977102864',
    projectId: 'our-chat-31921',
    storageBucket: 'our-chat-31921.appspot.com',
    iosBundleId: 'com.example.ourChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1VrN6pL6cx7Y0GQhbmzq8aFsLd1o2r7g',
    appId: '1:942977102864:ios:7ff252560089fbc85cc695',
    messagingSenderId: '942977102864',
    projectId: 'our-chat-31921',
    storageBucket: 'our-chat-31921.appspot.com',
    iosBundleId: 'com.example.ourChat.RunnerTests',
  );
}
